### ISSUE TITLE
Tracking issue: Support for Doxygen commands

### ISSUE THREAD

**Issue by Techie-Pi** [Techie-Pi/doxygen-rs#1]
**This info is currently outdated!**

<details>
<summary>List of Doxygen commands and their status</summary>

- [ ] \addtogroup <name> [(title)]
- [ ] \callgraph
- [ ] \hidecallgraph
- [ ] \callergraph
- [ ] \hidecallergraph
- [ ] \showrefby
- [ ] \hiderefby
- [ ] \showrefs
- [ ] \hiderefs
- [ ] \category <name> [<header-file>] [<header-name>]
- [x] ~~\class <name> [<header-file>] [<header-name>]~~ - Won't be supported
- [ ] \concept <name>
- [ ] ~~\def <name>~~ - Constant defs are not supported by bindgen anyway
- [ ] \defgroup <name> (group title)
- [ ] \dir [<path fragment>]
- [x] ~~\enum <name>~~ Won't be supported
- [ ] \example['{lineno}'] <file-name>
- [ ] \endinternal
- [ ] \extends <name>
- [ ] \file [<name>]
- [ ] \fn (function declaration)
- [ ] \headerfile <header-file> [<header-name>]
- [ ] \hideinitializer
- [ ] \idlexcept <name>
- [ ] \implements <name>
- [ ] \ingroup (<groupname> [<groupname>]*)
- [ ] \interface <name> [<header-file>] [<header-name>]
- [ ] \internal
- [ ] \mainpage [(title)]
- [ ] \memberof <name>
- [x] \name [(header)]
- [ ] \namespace <name>
- [ ] \nosubgrouping
- [ ] \overload [(function declaration)]
- [ ] \package <name>
- [ ] \page <name> (title)
- [ ] \private
- [ ] \privatesection
- [ ] \property (qualified property name)
- [ ] \protected
- [ ] \protectedsection
- [ ] \protocol <name> [<header-file>] [<header-name>]
- [ ] \public
- [ ] \publicsection
- [ ] \pure
- [ ] \relates <name>
- [ ] \related <name>
- [ ] \relatesalso <name>
- [ ] \relatedalso <name>
- [ ] \showinitializer
- [ ] \static
- [ ] \struct <name> [<header-file>] [<header-name>]
- [ ] \typedef (typedef declaration)
- [ ] \union <name> [<header-file>] [<header-name>]
- [ ] \var (variable declaration)
- [x] ~~\vhdlflow [(title for the flow chart)]~~ Won't be supported
- [ ] \weakgroup <name> [(title)]
- [ ] \attention { attention text }
- [ ] \author { list of authors }
- [ ] \authors { list of authors }
- [x] \brief { brief description }
- [ ] \bug { bug description }
- [ ] \cond [(section-label)]
- [ ] \copyright { copyright description }
- [ ] \date { date description }
- [x] \deprecated { description }
- [x] \details { detailed description }
- [ ] \noop ( text to be ignored )
- [ ] \raisewarning ( text to be shown as warning )
- [ ] \else
- [ ] \elseif (section-label)
- [ ] \endcond
- [ ] \endif
- [ ] \exception <exception-object> { exception description }
- [ ] \if (section-label)
- [ ] \ifnot (section-label)
- [ ] \invariant { description of invariant }
- [x] \note { text }
- [ ] \par [(paragraph title)] { paragraph }
- [x] \param '['dir']' <parameter-name> { parameter description }
- [ ] \parblock
- [ ] \endparblock
- [ ] \tparam <template-parameter-name> { description }
- [ ] \post { description of the postcondition }
- [ ] \pre { description of the precondition }
- [ ] \remark { remark text }
- [ ] \remarks { remark text }
- [ ] \result { description of the result value }
- [x] \return { description of the return value }
- [x] \returns { description of the return value }
- [x] \retval <return value> { description }
- [x] \sa { references }
- [x] \see { references }
- [x] \short { short description }
- [ ] \since { text }
- [ ] \test { paragraph describing a test case }
- [ ] \throw <exception-object> { exception description }
- [ ] \throws <exception-object> { exception description }
- [x] \todo { paragraph describing what is to be done }
- [ ] \version { version number }
- [x] \warning { warning message }
- [ ] \xrefitem <key> "(heading)" "(list title)" { text }
- [ ] \addindex (text)
- [ ] \anchor <word>
- [ ] \cite <label>
- [ ] \endlink
- [ ] \link <link-object>
- [x] \ref <name> ["(text)"]
- [ ] \refitem <name>
- [ ] \secreflist
- [ ] \endsecreflist
- [ ] \subpage <name> ["(text)"]
- [ ] \tableofcontents['{'[option[:level]][,option[:level]]*'}']
- [ ] \section <section-name> (section title)
- [ ] \subsection <subsection-name> (subsection title)
- [ ] \subsubsection <subsubsection-name> (subsubsection title)
- [ ] \paragraph <paragraph-name> (paragraph title)
- [ ] \dontinclude['{lineno}'] <file-name>
- [ ] \include['{'option'}'] <file-name>
- [ ] \includelineno <file-name>
- [ ] \includedoc <file-name>
- [ ] \line ( pattern )
- [ ] \skip ( pattern )
- [ ] \skipline ( pattern )
- [ ] \snippet['{'option'}'] <file-name> ( block_id )
- [ ] \snippetlineno <file-name> ( block_id )
- [ ] \snippetdoc <file-name> ( block_id )
- [ ] \until ( pattern )
- [ ] \verbinclude <file-name>
- [ ] \htmlinclude ["[block]"] <file-name>
- [ ] \latexinclude <file-name>
- [ ] \rtfinclude <file-name>
- [ ] \maninclude <file-name>
- [ ] \docbookinclude <file-name>
- [ ] \xmlinclude <file-name>
- [x] \a <word>
- [ ] \arg { item-description }
- [ ] \b <word>
- [ ] \c <word>
- [x] \code['{'<word>'}']
- [ ] \copydoc <link-object>
- [ ] \copybrief <link-object>
- [ ] \copydetails <link-object>
- [ ] \docbookonly
- [ ] \dot ["caption"] [<sizeindication>=<size>]
- [x] \emoji "name"
- [ ] \msc ["caption"] [<sizeindication>=<size>]
- [ ] \startuml ['{'option[,option]'}'] ["caption"] [<sizeindication>=<size>]
- [ ] \dotfile <file> ["caption"] [<sizeindication>=<size>]
- [ ] \mscfile <file> ["caption"] [<sizeindication>=<size>]
- [ ] \diafile <file> ["caption"] [<sizeindication>=<size>]
- [x] \e <word>
- [x] \em <word>
- [x] \endcode
- [ ] \enddocbookonly
- [ ] \enddot
- [ ] \endmsc
- [ ] \enduml
- [ ] \endhtmlonly
- [ ] \endlatexonly
- [ ] \endmanonly
- [ ] \endrtfonly
- [ ] \endverbatim
- [ ] \endxmlonly
- [ ] \f$
- [ ] \f(
- [ ] \f)
- [ ] \f[
- [ ] \f]
- [ ] \f{environment}{
- [ ] \f}
- [ ] \htmlonly ["[block]"]
- [ ] \image['{'option[,option]'}'] <format> <file> ["caption"] [<sizeindication>=<size>]
- [ ] \latexonly
- [ ] \manonly
- [ ] \li { item-description }
- [ ] \n
- [ ] \p <word>
- [ ] \rtfonly
- [ ] \verbatim
- [ ] \xmlonly
- [ ] \\
- [ ] \@
- [ ] \~[LanguageId]
- [ ] \&
- [ ] \$
- [ ] \#
- [ ] \<
- [ ] \>
- [ ] \%
- [ ] \"
- [ ] \.
- [ ] \=
- [ ] \::
- [ ] \|
- [ ] \--
- [ ] \---
</details>

Rel: https://github.com/rust-lang/rust-bindgen/issues/955
